### ISSUE TITLE
請問如何自定義文章縮圖?

### ISSUE THREAD

**Issue by Johnny850807** [Halyul/hexo-theme-mdui#103]
已細讀文件但還是未找到
能夠自定義每個文章之縮圖的方法

感激不盡

**Comment by Halyul** [comment]
文档页https://halyul.github.io/hexo-theme-mdui/#/zh-cn/advanced?id=缩略图
配置样例
https://raw.githubusercontent.com/Halyul/halyul.github.io/master/posts/table/table.md
