### ISSUE TITLE
手机屏幕首页title显示问题

### ISSUE THREAD

**Issue by zHElEARN** [Halyul/hexo-theme-mdui#108]

**Comment by zHElEARN** [comment]
![](https://i.loli.net/2019/06/19/5d0a2a5f4e55311114.png)

**Comment by Halyul** [comment]
What is the issue? It seems that everything is working correctly

**Comment by zHElEARN** [comment]
@Halyul 因为左边的字是白色而右边的黑色字加了drawer的shadow:disappointed_relieved:

**Comment by Halyul** [comment]
That's an intentional design.

**Comment by zHElEARN** [comment]
感觉有些硬核（？）
