### ISSUE TITLE
Search页面“联系我”定位错误

### ISSUE THREAD

**Issue by OhYee** [Halyul/hexo-theme-mdui#24]
Search页面 上面的联系我位置跑到左侧，导致弹出菜单箭头位置不对

![tim 20170607000450](https://user-images.githubusercontent.com/13498329/26839371-6b3f78ca-4b15-11e7-994e-1c9d2cc43f72.png)

**Comment by Halyul** [comment]
我明天确认一下这个问题 不过估计会在下个版本发布时修复
(不过下个版本是什么时候我也不知道啊 我也很绝望啊

**Comment by OhYee** [comment]
哈哈哈，期待新版本。
等过几天考完试我就把主题换成这个试试。

hexo那么多主题里别具一格，赞~

**Comment by EYHN** [comment]
祝你考试顺利！

**Comment by Halyul** [comment]
fixed since [9b49dc4](https://github.com/Halyul/hexo-theme-mdui/commit/01dfe9b5f74bc142f298671188e54be39a602643)
