### ISSUE TITLE
I HAVE NO IDEA ON NEXT VERSION!

### ISSUE THREAD

**Issue by Halyul** [Halyul/hexo-theme-mdui#45]
I don't know what should I add/change/modify in the next version, my dear users, do you have any idea? 
Just leave your comment! You may have chances to see your idea appeared in the next version! 
~~But I think there will be no reply???~~

**Comment by Zchengtui** [comment]
...

**Comment by Zchengtui** [comment]
把QQ的分享修一下...
![20170721183254](https://user-images.githubusercontent.com/30227432/28460099-15ca7b32-6e43-11e7-8761-7f4161bb8e99.png)

**Comment by Halyul** [comment]
@Zchengtui Received

**Comment by Zchengtui** [comment]
也许可以试着内置Gitment和livere评论功能

**Comment by Halyul** [comment]
@Zchengtui 我觉得我现在的做法可能会很好 因为评论服务太多了 并且各方的配置可能要求不同 很难做到内置 倒不如让用户自行添加 我觉得我的添加方式算非常友好的了٩(๑òωó๑)۶

**Comment by Zchengtui** [comment]
OK.

**Comment by Zchengtui** [comment]
不知道为什么标题字体看起来比较扎眼......是DPI的问题吗？

也许可以对比一下：
- <https://blog.zacco.site>
![snipaste_20170815_121232](https://user-images.githubusercontent.com/30795138/29315492-192cc372-81f6-11e7-9511-5fd179196f7f.png)
- <https://blog.halyul.cc>
![snipaste_20170815_121126](https://user-images.githubusercontent.com/30795138/29315522-3559df9e-81f6-11e7-9abf-65cdaecaab1d.png)

系统信息：
操作系统：Windows 8.1 企业版
屏幕分辨率：1366x768
浏览器：Google Chrome 60.0.3112.90（正式版本） （32 位）

**Comment by Halyul** [comment]
@Zchengtui 我会试着调整一下，我也不知道具体是什么问题…

**Comment by Zchengtui** [comment]
@Halyul Okay......

**Comment by EYHN** [comment]
@Halyul  你可以加入css代码
```
body {
  -webkit-font-smoothing: antialiased;
}
```

@Zchengtui 我在windows上本没有发现这个问题，请确保你有打开 windows cleartype 可能会改善字体显示问题

**Comment by Halyul** [comment]
@Zchengtui 我在win10上并没有这个问题，请检查您电脑的设置

**Comment by Zchengtui** [comment]
@Halyul @EYHN 我电脑Cleartype的锅= =

**Comment by yangchuansheng** [comment]
可以加入微信分享

**Comment by yihuishou** [comment]
也许可以让 .md 文章中可以插入表情？ QwQ

**Comment by yihuishou** [comment]
now 主题中 点击文章缩略图 应该也可以查看文章的说~ ？

**Comment by Halyul** [comment]
@yangchuansheng 微信分享不会添加，过于小众了。
@yihuishou 
- md插入表情有考虑，暂时没有思路
- 没有这种操作

**Comment by yihuishou** [comment]
也许可以加入自定义字体API，google apl 不是很稳定的说  (ฅ´ω`ฅ)

**Comment by Halyul** [comment]
@yihuishou 现在就可以通过自定义头部来自己弄字体，google fonts在大陆已经有服务器了，不存在不稳定的

**Comment by FeiyangOnline** [comment]
添加HyperComment評論系統的以及Algolia搜索服務的支持?

**Comment by Halyul** [comment]
@FeiyangOnline 我会在我有时间的时候看看

**Comment by yangchuansheng** [comment]
现在支持表格样式了吗

**Comment by Halyul** [comment]
@yangchuansheng 已支持

**Comment by yangchuansheng** [comment]
具体关联到哪些代码，可以给我指明一下吗

**Comment by Halyul** [comment]
@yangchuansheng https://github.com/Halyul/hexo-theme-mdui/blob/master/scripts/lib/table.js

**Comment by kriaeth** [comment]
倒是有一个小建议qwq感觉博客正文部分的width小了qwq占大半个屏幕会舒服一些把 感觉现在的有点空虚

**Comment by Halyul** [comment]
@kriaeth 如果太长的话，读者看同一行会用很长时间，导致看下一行的时候会找不到哪里才是下一行，这个是有我自己的考量的

**Comment by Enter-tainer** [comment]
主页卡片之间的间隙和G+相比小了一点
MDUI
![image](https://user-images.githubusercontent.com/25521218/34905974-8bc91772-f89e-11e7-9561-ef67e137804f.png)
G+
![b q295n5g 0_7 07t2 7](https://user-images.githubusercontent.com/25521218/34906002-f7188292-f89e-11e7-8b14-8782b63f6a4d.png)

**Comment by Enter-tainer** [comment]
另一个设计上的问题
![image](https://user-images.githubusercontent.com/25521218/34906015-351234b2-f89f-11e7-94ba-1eacc9ac2ba2.png)
根据md设计规范，卡片上的元素不应该有阴影
图中“技术”的那个图标在鼠标悬停之后有阴影效果
感觉这个更适合把背景做成透明的（而不是有一个灰色的圆形背景）

**Comment by Halyul** [comment]
卡片距离问题：这是因为我是固定了16px，而google plus上的是自适应的2%
阴影问题：这个在google plus上也有
