### ISSUE TITLE
文章标题较长时，下划线效果只能显示单行？

### ISSUE THREAD

**Issue by nonnone** [Halyul/hexo-theme-mdui#51]
文章标题较长时，下划线效果只能显示单行？
<img width="457" alt="2017-08-06 9 11 31" src="https://user-images.githubusercontent.com/26184260/29001825-d2f8bb94-7ac6-11e7-8fc3-57e80122b331.png">

菜单页面悬浮且透明是原设计目的吗？阅读文章时向左拖拽，文字会重叠。
<img width="1220" alt="2017-08-06 9 10 57" src="https://user-images.githubusercontent.com/26184260/29001875-46de2b20-7ac7-11e7-813c-7325f18ee694.png">

Galleries页面相册默认图片无法显示
<img width="621" alt="2017-08-06 4 51 51" src="https://user-images.githubusercontent.com/26184260/29001896-a839befc-7ac7-11e7-9f2d-e8800df98399.png">

<img width="313" alt="2017-08-06 4 53 56" src="https://user-images.githubusercontent.com/26184260/29001905-186bab86-7ac8-11e7-8ddd-97c578934b28.png">
此处改为img标签图片显示正常，相册描述超过边框后改为ellipsis是不是会更好？

**Comment by Halyul** [comment]
A1: 这个是mdui的bug，目前这个效果mdui已经去掉了，但是还没有release

A2: 这个问题在我测试时并未发现，我有空了我再看看，我似乎重现不出来

A3: 相册这个是bug，当时用了lazyload，去掉的时候忘记把标签改回来了，近几天我修复一下相册相关问题吧

**Comment by nonnone** [comment]
@Halyul 
关于Q2，应该可以重现，不过用鼠标拖动页面下方的滚动条才能实现，你可能用的鼠标。用触控板手势，手贱一滑就这样了。
<img width="1218" alt="2017-08-06 6 45 28" src="https://user-images.githubusercontent.com/26184260/29002552-8611baae-7ad7-11e7-8899-fdcb4556120f.png">

**Comment by Halyul** [comment]
不对啊，应该不存在x轴的滚动条才对的啊。。。。发生了什么.....

**Comment by nonnone** [comment]
@Halyul 
就是本来不应该出现x轴滚动条，然而它出现了。你那边不会出现？

**Comment by Halyul** [comment]
并不会，请问您用的是什么设备和浏览器呢

**Comment by nonnone** [comment]
macOS Sierra 10.12.6 ，Chrome 60.0.3112.90

**Comment by Halyul** [comment]
好的，晚点我试试

**Comment by nonnone** [comment]
还有一个问题，电脑点开关于页面是可以点左右两边空余位置关闭，但移动端x轴方向的空间铺满，必须后退或刷新才能关闭关于页面。
![media-20170806](https://user-images.githubusercontent.com/26184260/29002794-11fdd94e-7add-11e7-8b77-cb140d73bc3d.png)

**Comment by Halyul** [comment]
了解，这个问题会一起修复

**Comment by Halyul** [comment]
我在相同环境下试了一下，并不会复现....所以暂时无解。如果可以的话，您可以录一个操作视频给我看看

**Comment by nonnone** [comment]
@Halyul 
在窗口宽度不大时，是没有x轴滚动条的；但拉伸或全屏时就出现了。开启了无痕模式也一样，已排除Chrome扩展影响的可能性。没有使用扩展的Safari也同样拉伸后出现问题。具体看视频。
https://koriste-my.sharepoint.com/personal/a_koriste_onmicrosoft_com/_layouts/15/guestaccess.aspx?docid=0f6211dcae016435fa6470bdfdb13375b&authkey=AaV9Ch4yLa-lJwKF9TmcdvY

**Comment by Halyul** [comment]
emmm了解，然而悲伤的是mba刚好炸了，我调试不了了...

**Comment by Halyul** [comment]
好了我试出来了...css应该没写好...

**Comment by nonnone** [comment]
感觉像是Responsive方面没有写好，那剩下的交给你了。

**Comment by Halyul** [comment]
好了，谢谢您的反馈，这些问题均在1.4.7得到修复
