### ISSUE TITLE
表格没有添加mdui中的样式吗？

### ISSUE THREAD

**Issue by nonnone** [Halyul/hexo-theme-mdui#55]
表格(table)没有添加mdui中的样式吗？https://www.mdui.org/docs/table

**Comment by Halyul** [comment]
@nonnone 并没有哦，后续可能会考虑添加，目前并没有这样的考虑

**Comment by nonnone** [comment]
好的，我自行解决吧。

**Comment by Halyul** [comment]
将在下一个大版本考虑添加此功能

**Comment by yangchuansheng** [comment]
新版本好像还是没有表格样式

**Comment by Halyul** [comment]
@yangchuansheng 对 因为这个issue还没关

**Comment by yangchuansheng** [comment]
不准备加上去吗

**Comment by Halyul** [comment]
@yangchuansheng 暂时没有时间
