### ISSUE TITLE
数学公式支持

### ISSUE THREAD

**Issue by yangchuansheng** [Halyul/hexo-theme-mdui#58]
这个主题支不支持数学公式啊，我配置了之后不起作用

**Comment by Halyul** [comment]
@yangchuansheng 这个我并没配置过…我会尽量在下一个小版本修复

**Comment by yangchuansheng** [comment]
好的，坐等，还有关于评论的部分，也有一些问题，找不到layout/_custom/custom_comment.ejs这个文件啊，请问你的来必力是怎么配置的

**Comment by Halyul** [comment]
@yangchuansheng 文档中有写哦 这些文件是需要您自己建立的呢

**Comment by yangchuansheng** [comment]
网易云的评论可以用吗

**Comment by Halyul** [comment]
@yangchuansheng 都可以

**Comment by yangchuansheng** [comment]
又发现一个问题，这个主题插入markdown表格好像有问题

**Comment by Halyul** [comment]
@yangchuansheng 是直接用HTML代码有问题 还是语法的渲染问题 最好提供截图让我参考一下

**Comment by yangchuansheng** [comment]
![image](https://user-images.githubusercontent.com/15308462/29700255-b4fd492e-8995-11e7-91c0-b7b18e04ac11.png)

**Comment by yangchuansheng** [comment]
这是语法:
![image](https://user-images.githubusercontent.com/15308462/29700275-d3c03902-8995-11e7-9511-210ed15a3472.png)

这是效果：
![image](https://user-images.githubusercontent.com/15308462/29700268-c8dd0d44-8995-11e7-89cb-589b7a077590.png)

**Comment by Halyul** [comment]
@yangchuansheng 因为我这个版本的mdui没有带上table组件 当时并未考虑在文章中会有直接使用table组件的情况
issue#55

**Comment by yangchuansheng** [comment]
下个版本可以考虑加上去

**Comment by EYHN** [comment]
https://github.com/Halyul/hexo-theme-mdui/commit/3d23e82986024e365fc07e899e77c0ddd8c03503

**Comment by yangchuansheng** [comment]
还有一个问题，在1920x1080的屏幕上显示的是这样，好像不能自适应啊

![image](https://user-images.githubusercontent.com/15308462/29701537-e509418c-899e-11e7-9861-836dfb314258.png)

**Comment by Halyul** [comment]
@yangchuansheng 看起来似乎没有毛病呀…您说的 自适应 是什么意思

**Comment by yangchuansheng** [comment]
就是文章的宽度能不能再大一点，然后小标题列表放到最右边

**Comment by Halyul** [comment]
@yangchuansheng 设计就是这样的😂

**Comment by yangchuansheng** [comment]
文章的宽度不能自动调大？

**Comment by Halyul** [comment]
@yangchuansheng 限制了宽度的

**Comment by yangchuansheng** [comment]
可以改代码调吗，求指导一下

**Comment by Halyul** [comment]
@yangchuansheng 您可以使用自定义样式 我在文档中有提到 不过具体是改什么就需要您直接去找到了
