### ISSUE TITLE
添加自定义页面

### ISSUE THREAD

**Issue by yangchuansheng** [Halyul/hexo-theme-mdui#59]
关于添加友情链接的部分我看的不是很懂，在主题的配置文件里面应该怎么填

**Comment by Halyul** [comment]
[入口文件](https://github.com/Halyul/theme-mdui-ci/blob/master/source/friends/index.md)
[数据文件](https://github.com/Halyul/theme-mdui-ci/blob/master/source/_data/friends.yml)

**Comment by yangchuansheng** [comment]
![image](https://user-images.githubusercontent.com/15308462/29708270-b5df4cc8-89ba-11e7-9f06-299848f82efa.png)
按照你的这个配置文件配了之后还是不显示，这个md后面的值是什么意思

**Comment by yangchuansheng** [comment]
![image](https://user-images.githubusercontent.com/15308462/29708345-e8192bd2-89ba-11e7-96de-582488009774.png)

按照你的这个配置文件配了之后还是不显示，这个md后面的值是什么意思

**Comment by Halyul** [comment]
@yangchuansheng 图标名称 请认真读文档
