### ISSUE TITLE
代码高亮模块工作不正常~~

### ISSUE THREAD

**Issue by yihuishou** [Halyul/hexo-theme-mdui#63]
使用 npm install prismjs --save 后
程序依旧无法找到prismjs

**Comment by yihuishou** [comment]
TypeError: Cannot set property 'keyword' of undefined
    at Object.extend (e:\Hexo\node_modules\prismjs\components\prism-core.js:74:15)

**Comment by yihuishou** [comment]
说明文档里没有写明切换语言的设置…… zh-cn 不好用 必须是 zh-CN

**Comment by Halyul** [comment]
@yihuishou 染色插件这个问题请问是如何出现的呢？能否给我一个复现步骤？
语言设置问题是跟着HEXO官方文档的，请认真阅读官方文档

**Comment by yihuishou** [comment]
在正常安装Hexo之后，指定使用乃的主题之后就是这样~
目录结构如下：
$ npm list --depth 0
hexo-site@0.0.0 E:\Hexo
+-- hexo@3.3.9
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-search@2.1.1
+-- hexo-generator-searchdb@1.0.8
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.2
`-- prismjs@1.8.1

（莫非是我win32 系统的锅？ 小声……）

**Comment by yihuishou** [comment]
菜单栏前面的图标和文章右上角的图标在手机端浏览会缺失~
麻烦说明一下修改的方法~ ovo

**Comment by yihuishou** [comment]
文章底部许可协议和md文件路径显示区域可以去除吗~？ 在配置文档中似乎没有相关信息~

**Comment by Halyul** [comment]
- 这个染色问题我还真的不知道是怎么回事 @EYHN 你来看看？
- 感觉缺失的话是你的问题啊，我实测是没有的，你访问我的站点会出现这个问题吗？
- 许可协议的话，你只需要留空就好了

**Comment by yihuishou** [comment]
你的站点菜单都是图标哇~  咱这边看到的都是一个 ’方块‘ 文字在那里的说~ QAQ

**Comment by Halyul** [comment]
能否将配置文件贴上来看看呢？

**Comment by yihuishou** [comment]
# CDN for mathjax
location: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

# style
style:
  scheme: 'now'
  bg_img: /img/bg.png
  avatar: /img/isme.png
  slogan: "喵·帕·斯"
  hoverable: true

# HTML head
head:
  favicon: /img/isme.png
  high_res_favicon: /img/isme.png
  apple_touch_icon: /img/isme.png
  keywords: blog, hexo, mdui

# color
color:
  primary_color: "indigo"
  accent_color: "blue"
  layout:
  random:
  bg_color: "#eeeeee"

# appbar
appbar:
  title: "(ฅ´ω`ฅ)"
  search: false

index:
  welcome: "欢迎来到我的Blog(๑＞ڡ＜)☆"
  notification: false

# post settings
post:
  entry_excerpt: 80
  qr_code: false
  prism:
    theme: coy
    line_number: true
  license:
    name: 'CC BY-NC-SA 4.0'
    link:  'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh'
  word_count:
  read_time:
  toc_list_number: true
  donate:
#    wechat:
#      link: /img/avatar.png
#      fa: 'fa-wechat'
#    paypay:
#      link: 'https://paypal.com'
#      fa: 'fa-paypal'


share_menu:
#  rss: false
#  weibo: false
#  twitter: true
#  facebook: true
#  googleplus: true
#  linkedin: true
  qq: true
#  telegram: false

comment:
    use:
    shortname:

# pagination
# github@zllovesuki
pagination: 2

# footer
footer:
  since: 2017
  ICP:
  image:

# Plugins
busuanzi:
#  all_site_uv: true
#  post_pv: true
#  busuanzi_pure_mini_js: "//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

service_woker:

about_me: true

pace: false

random_pics: 44

pages:
#  Test1:
#    link: "/myfriends"
#    md: "&#xe0ba;"
#  Test2:
#    link: "/apply-for-link"
#    fa: "fa-child"
#  Test3:
#    link: "/timeline"
#    md: "home"
#  Test4:
#    cascade: true
#    md: 'home'
#    pages:
#      TEST1:
#        link: "/myfriends"
#        md: "&#xe5ca;"
#      TEST2:
#        link: "/timeline"
#        md: "home"

sns:
#  Twitter:
#    link: https://twitter.com
#    fa: 'fa-twitter'
#  Facebook:
#    link: https://facebook.com
#    null_icon: true

# Vendors
vendors:
  fonts_min_css: fonts.useso.com
  style_min_css:
  js_min_js:
  outdatedbrowser_min_js:
  pace_min_js:
  pace_style_css:

**Comment by yihuishou** [comment]
大部分图标都显示成  ""

**Comment by Halyul** [comment]
@yihuishou 你看看控制台是否报错

**Comment by yihuishou** [comment]
@Halyul 控制台除了之前找不到代码着色器的错误意外，没有其他的了

**Comment by yihuishou** [comment]
@Halyul  就是这个样子的&#xe0ba https://yihuishou.github.io

**Comment by Halyul** [comment]
@yihuishou l浏览器控制台

**Comment by yihuishou** [comment]
@Halyul 没有错误~

**Comment by Halyul** [comment]
@yihuishou ....额你现在是全部图标都不显示吗？

**Comment by yihuishou** [comment]
@Halyul yes~ QAQ

**Comment by EYHN** [comment]
我需要 node 版本、 npm 版本、package.json。

**Comment by Halyul** [comment]
@yihuishou 你这个是全新clone还是pull的？如果是前者，请你重新clone一次试试，我发现你的文件里面有点不科学的地方，我已经弃用的地方重新出现了

**Comment by Halyul** [comment]
染色那里因为prism那里更新了，我内置的调用没跟上而导致染色出错，我会尽快解决。
如果你急需使用的话，请手动安装prismjs的1.6.0版本

**Comment by EYHN** [comment]
prism.js 1.6.0 可以用

```
npm install --save prismjs@1.6.0
```

**Comment by yihuishou** [comment]
@Halyul  cdn?? 指的是哪一个的说？

**Comment by yihuishou** [comment]
@EYHN 好用了 QwQ

**Comment by yihuishou** [comment]
@Halyul 话说
```
font-matter 中加入
export_md: false
```
这段配置是在主题中自行加入的吗？

**Comment by yihuishou** [comment]
@Halyul 在mdui/layout/_custom目录下新建两个空文件custom_head.ejs和custom_js.ejs即可让警告消失
要不要在配置文件里加个选项是否开启自定义头？ QwQ

**Comment by Halyul** [comment]
@yihuishou 这是一个不错的主意

**Comment by Halyul** [comment]
这里补充说一下，
- fonts.min.css是需要配置到自己的CDN服务器上的，并没有公共CDN版本，同时该处是填入完整的文件地址
- 代码高亮问题已经在开发版中修复，新用户需要安装另一个插件，老用户只要不升级prismjs就没问题
