### ISSUE TITLE
关于画廊和自定义菜单的问题

### ISSUE THREAD

**Issue by yihuishou** [Halyul/hexo-theme-mdui#64]
说明文档里的描述太过简单，没有例子。

**Comment by yihuishou** [comment]
单画廊中左上角的返回图标不能正常跳出画廊 QwQ

**Comment by yihuishou** [comment]
自定义菜单最多只支持四个吗？

**Comment by Halyul** [comment]
- 跳不出画廊是什么回事？
- 自定义菜单是侧边栏的那个吗？如果是，理论上可以添加无限个

**Comment by yihuishou** [comment]
是导航栏上的那个……

**Comment by Halyul** [comment]
@yihuishou 似乎主题并不存在导航栏吧。。。

**Comment by yihuishou** [comment]
![example](https://user-images.githubusercontent.com/26241263/30944048-e555c874-a427-11e7-86e9-080437f8b803.png)

**Comment by yihuishou** [comment]
可展开的自定义侧边栏 二级菜单图标好像不能显示？

**Comment by yihuishou** [comment]
！> we

**Comment by Halyul** [comment]
@yihuishou 画廊我这里没有问题。。。
侧边栏可展开的选项不能用图标

**Comment by yihuishou** [comment]
画廊的封面和logo无法使用站点`source`中的图片吗 ？
