### ISSUE TITLE
画廊在移动端页面头像显示问题~

### ISSUE THREAD

**Issue by yihuishou** [Halyul/hexo-theme-mdui#67]
![bug](https://user-images.githubusercontent.com/26241263/30950094-1dbbc4c8-a44d-11e7-9a21-cccf1165fb16.png)
![qq 20170926091359](https://user-images.githubusercontent.com/26241263/30950101-27347de2-a44d-11e7-8fdf-a7b8ca69e7e0.jpg)

**Comment by Halyul** [comment]
这是什么样式下出现的？

**Comment by yihuishou** [comment]
@Halyul now

**Comment by Halyul** [comment]
令人窒息。。。明天修
