### ISSUE TITLE
关于修复画廊头像问题时编译器的错误提示

### ISSUE THREAD

**Issue by yihuishou** [Halyul/hexo-theme-mdui#69]
![bug](https://user-images.githubusercontent.com/26241263/31041567-fde47d10-a5c9-11e7-991e-dfad690f4d6f.jpg)

版本1.50 替换了1.51中的修复画廊头像的代码 `now`成功修复了

**Comment by yihuishou** [comment]
似乎`plus`修正之后变得比之前还难看了 `(/ω＼)`

##### 修正前：
![before-fixed](https://user-images.githubusercontent.com/26241263/31041667-dcaf2652-a5cb-11e7-80d3-87bba31ddc33.jpg)

##### 修正后：
![after-fix](https://user-images.githubusercontent.com/26241263/31041668-e2c3bb20-a5cb-11e7-8c1b-a81a5d7ef08e.jpg)

**Comment by Halyul** [comment]
@yihuishou …忘记看了 我的锅

**Comment by yihuishou** [comment]
![other](https://user-images.githubusercontent.com/26241263/31041775-5c058d46-a5cd-11e7-8924-16700a2dcaca.jpg)

### 也许……加点边距能好看一些的说？~  `(/ω＼)`
