### ISSUE TITLE
qrcode是什么？？？

### ISSUE THREAD

**Issue by zhujikuan** [Halyul/hexo-theme-mdui#84]
ERROR F:\hexo\themes\mdui\layout\post.ejs:41
    39|         <% } %>
    40|       </div>
 >> 41|       <%- partial('_partials/menu/qrcode') %>
    42|       <%- partial('_partials/menu/share/post') %>
    43|     </div>
    44|   </div>

F:\hexo\themes\mdui\layout\_partials\menu\qrcode.ejs:10
    8|         <%= __('posts.qr_code') %>
    9|       </li>
 >> 10|         <img class="mdui-img-fluid" src="<%- qrcode(url, {
    11|           margin: 2
    12|         }) %>" style="cursor: auto">
    13|     </ul>

qrcode is not defined

**Comment by Halyul** [comment]
@zhujikuan https://halyul.github.io/hexo-theme-mdui/#/zh-cn/plugins?id=qr_code
