### ISSUE TITLE
Invalid flags supplied to RegExp constructor 'gs'？

### ISSUE THREAD

**Issue by Bruce-zxy** [Halyul/hexo-theme-mdui#88]
**操作系统**：window 7
**MDUI版本**：最新Clone版
**Package配置**：
`
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^2.1.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^2.0.1",
    "node-prismjs": "^0.1.1",
    "node-sass": "^4.9.0",
    "node-sass-magic-importer": "^5.1.3",
    "prismjs": "^1.15.0"
  }
}
`

**问题截图**：
![image](https://user-images.githubusercontent.com/22904758/41840723-0a630ece-7899-11e8-99e9-3ee82ed4b81b.png)

**问题重现**：
在任意一个站点下cd到theme后git clone下代码，在npm install之后执行hexo g发生以上错误

**问题排除过程**：
我曾尝试版本回退到release 2.0
![image](https://user-images.githubusercontent.com/22904758/41841316-8b5dcba8-789a-11e8-962f-9ebad259cfab.png)
结果发现一切是正常的
![image](https://user-images.githubusercontent.com/22904758/41841325-94231a7c-789a-11e8-9dbd-24f5ed80a1cc.png)

**Comment by Halyul** [comment]
请将以下module升级:
- nodeJS => 8.x
- hexo => 3.8
- hexo-renderer-ejs => 0.3.1

**Comment by Bruce-zxy** [comment]
Emmmm........
![image](https://user-images.githubusercontent.com/22904758/41849922-4fabbe42-78b5-11e8-9280-43552e1e9600.png)
我说咋一直提示我找不到package....

**Comment by Halyul** [comment]
@Bruce-zxy Hexo.io
