### ISSUE TITLE
post title bug report

### ISSUE THREAD

**Issue by ericclose** [Halyul/hexo-theme-mdui#90]
很抱歉，在此我想问一个问题。
# 文章标题过长显示问题（bug?）
![screenshot_chrome_20181029-151810](https://user-images.githubusercontent.com/34526560/47635916-8bfaa400-db91-11e8-87fb-c7cce904c516.png)

我去你的站点 https://halyul.github.io/ 看你的标题太长会换行的呀，我需要怎样才能做成像你这样的效果。
![screenshot](https://user-images.githubusercontent.com/34526560/47635921-95840c00-db91-11e8-9e90-c906117f5479.png)

很抱歉打扰您了，期待您的回复

**Comment by Halyul** [comment]
halyul.github.io 上的是旧版主题
新版的问题我有空就修复一下吧

**Comment by ericclose** [comment]
> halyul.github.io 上的是旧版主题
> 新版的问题我有空就修复一下吧

好的。谢谢

**Comment by ericclose** [comment]
与此同时，我发现不只是**首页**文章标题过长出现问题，而且在**文章页面**标题过长也会有个问题，标题的字会遮盖时间啥的，如下：
![post_title](https://user-images.githubusercontent.com/34526560/47892836-d67f6780-de94-11e8-9a63-151cc5539a68.png)

**Comment by Halyul** [comment]
文章页这个问题在demo上并没有问题，能否提供一下地址

**Comment by ericclose** [comment]
当我去掉 `mdui-text-truncate` 这个的时候就会这样，标题以省略号截断不大好吧，233

**Comment by ericclose** [comment]
![post_title](https://user-images.githubusercontent.com/34526560/47894063-9d96c100-de9b-11e8-94dd-1e0b9bacd62e.png)

**Comment by Halyul** [comment]
个人更改导致的bug请自行解决
