### ISSUE TITLE
sugestion

### ISSUE THREAD

**Issue by ericclose** [Halyul/hexo-theme-mdui#92]
请求添加对`gitalk`的支持。

**Comment by Halyul** [comment]
SPA版本下 支持的评论插件并不多 因为需要该插件支持[reset identifier](https://github.com/Halyul/hexo-theme-mdui/blob/b969c06c18c2af5e464f116c4cee48a619b6b364/layout/_partials/comment.ejs#L7) 否则所有评论都会出现在同一页面下
非SPA版本才会有正常的评论插件支持
需权衡利弊

**Comment by Halyul** [comment]
请自行根据[文档](https://halyul.github.io/hexo-theme-mdui/#/zh-cn/advanced?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%84%E8%AE%BA)添加
