### ISSUE TITLE
旧版主题搜索链接失效问题

### ISSUE THREAD

**Issue by yihuishou** [Halyul/hexo-theme-mdui#93]
`https://yihuishou.github.io/search/%2F2018%2F11%2F14%2F你好querySelector%2F` 不正常的URL

执行hexo clean hexo g hexo server 本地调试工作正常

但执行hexo d 之后链接就不知道为什么被转义了

**Comment by yihuishou** [comment]
我觉得好像计数统计也挂了~~ 嘿嘿~ double Kill~

**Comment by yihuishou** [comment]
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 骑士の物语
subtitle:
description:
author: 挥手の骑士
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://yihuishou.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
font-matter:
  export_md: false
# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: mdui

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:yihuishou/yihuishou.github.io

search:
  path: search.json
  field: post
  content: true

**Comment by Halyul** [comment]
请先尝试升级至1.5.4 确认问题是否存在

**Comment by yihuishou** [comment]
好的~ 我升级试一下

**Comment by yihuishou** [comment]
升级至 1.5.4 问题消失了，感谢
