### ISSUE TITLE
翻页出现错误:Failed to fetch

### ISSUE THREAD

**Issue by wekerSnail** [Halyul/hexo-theme-mdui#97]
hexo s在本地运行，翻页可以正常，上传到线上后，翻页会出现错误弹窗
![image](https://user-images.githubusercontent.com/30314164/51019595-67ba3b00-15b6-11e9-8301-fd24fd29a1f7.png)
 也有几率翻页翻出的第二页内容仍然是第一页的

**Comment by Halyul** [comment]
请提供一下线上地址

**Comment by wekerSnail** [comment]
> 请提供一下线上地址

https://wekersnail.github.io/

**Comment by Halyul** [comment]
确实出现了以前不存在的bug

**Comment by Halyul** [comment]
Fetch error这个bug只存在于github pages 当我使用我的服务器的时候 能够正常加载
原因是 https 请求被重定向至了 http 然后浏览器拒绝加载 我猜测是服务器的设置问题 暂时没有办法
 滚动不加载这个问题是JS获取页面相关数值出了问题 我在Windows下的Chrome上重现了 Edge则没有问题 Linux下的Chrome则是正常的 我只能通过更改加载方式来修复这个bug
