### ISSUE TITLE
菜单出现横向滚动条的问题

### ISSUE THREAD

**Issue by yihuishou** [Halyul/hexo-theme-mdui#99]
当配置的作者名称大于5个字符时
Plus主题下的菜单会出现横向滚动条。

版本：1.5.4

![qq 20190114131747](https://user-images.githubusercontent.com/26241263/51097422-e1dd0080-17fe-11e9-95d8-0d081f21249d.png)

**Comment by Halyul** [comment]
无法复现，请提供更详细的信息

**Comment by yihuishou** [comment]
嗯~ 配置站点所属名称过长时会出现…

**Comment by yihuishou** [comment]
模板加个换行好像就行了…
![qq 20190119134528](https://user-images.githubusercontent.com/26241263/51422814-880a7b00-1bf0-11e9-882e-7ee3eed29e52.png)
